---
- hosts: all
  vars_files:
    - vars.yml
  become: true

  tasks:
    - include: tasks/apt.yml
      tags: ['apt']
    
    - include: tasks/coin.yml
      tags: ['coin']

#    - include: tasks/rocksdb.yml
#      tags: ['rocksdb']

    - include: tasks/ssl.yml
      tags: ['ssl']

    - include: tasks/electrumx.yml
      tags:
        - electrumx